services:
  # MongoDB сервис
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - mongodb_data:/data/db
      - ./server/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  # Node.js бэкенд сервис
  backend:
    image: node:20-alpine
    container_name: node-backend
    working_dir: /app           # <-- здесь будем выполнять npm install
    command: sh -c "npm install && npm run dev:node"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/myapp?authSource=admin
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  # Frontend сервис на Parcel
  frontend:
    image: node:20-alpine
    container_name: parcel-frontend
    working_dir: /app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./client:/app
      - ./client/.parcel-cache:/app/.parcel-cache
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000
    ports:
      - "1234:1234"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
